### PR TITLE
Add LoongArch64 support

### PR DESCRIPTION
**Pull request by zjiaz**
Hi, 

[LoongArch](https://loongson.github.io/LoongArch-Documentation/README-EN.html) is a new RISC ISA developed by Loongson Technology, and now is a tier-3 backend in SpiderMonkey. We wish add LoongArch64 support in `authenticator-rs` for porting Firefox to our platform.

Thanks!

### CODE REVIEW

**Review by heiher — APPROVED** [review]
LGTM

**Review by jschanck — CHANGES_REQUESTED** [review]
Could you make this change on the `ctap2-2021` branch instead? The `hidwrapper.rs` and `ioctl_*` files are now in `src/transport/linux`.

**Comment by zjiaz** [comment]
> Could you make this change on the `ctap2-2021` branch instead? The `hidwrapper.rs` and `ioctl_*` files are now in `src/transport/linux`.

Hi John, thanks for your information, I have updated the patch and the target branch.
And this patch doesn't need to be merged to the `main` branch, right?

**Review by jschanck — APPROVED** [review]
Right, we're only working off the ctap2-2021 branch now. We'll merge it all over to main soon. Thanks!

**Pull request merged**
